### ISSUE TITLE
Allow JWT to be disabled completely for debgging

### ISSUE THREAD

**Issue by SpechtMagnus** [FIUS/Verleihsystem-TTF#106]
For debugging and development of new clients it would be useful to disable all JWT temporarily.

See [here](https://github.com/vimalloc/flask-jwt-extended/issues/143)

**Comment by buehlefs** [comment]
Allowing the jwt to be completely bypassed seems like a recipy for security holes in deployed applications.
For debugging with the swagger ui one can already set the json tokens as authorization to unlock all api calls. To get  a pair of always working tokens one can add a custom config file `/instance/total-tolles-ferleihsystem.conf` with the settings `JWT_ACCESS_TOKEN_EXPIRES=False` and `JWT_REFRESH_TOKEN_EXPIRES=False`.
The non expiring tokens can be saved for later use so unlocking authorized calls in the swagger ui only takes a few clicks and copy&paste.
