### ISSUE TITLE
Gegenstände VI - Duplikate

### ISSUE THREAD

**Issue by spethso** [FIUS/Verleihsystem-TTF#55]
<a href="https://github.com/gepperho"><img src="https://avatars3.githubusercontent.com/u/27412518?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gepperho](https://github.com/gepperho)**
_Friday Feb 16, 2018 at 15:29 GMT_
_Originally opened as https://github.com/spethso/Verleihsystem-master/issues/55_

----

Das System erkennt beim Erstellen eines Gegenstandes, ob es sich um ein Duplikat handelt und informiert den Administrator darüber
- Mit Bestätigung lässt sich der Gegenstand dennoch anlegen
- Mit Abbruch wird die Erstellung verworfen

**Comment by neumantm** [comment]
This is done by setting a sensible name schema and trying to create a item, with a name that already exists.
Creating the Item anyway is done by setting a custom name (e.g. <name>-version2)
