### ISSUE TITLE
Fehler beim Erstellen von Attributen

### ISSUE THREAD

**Issue by Arman-Mielke** [FIUS/Verleihsystem-TTF#68]
Wenn ich ein Attribut erstelle bekomm ich manchmal das hier:
```
Error while creating new resource under "attribute_definitions".
error._body.startsWith is not a function
```
Das Attribut wird dann nicht erstellt.

Ich weiß nicht, was man tun muss, um den Fehler hervorzurufen, scheint zufällig aufzutreten.

Workaround: Reload und nochmal probieren

Prio: 1/5, weil ein Workaround existiert

**Comment by Arman-Mielke** [comment]
Ich bekomm die gleiche Meldung auch ab und zu bei anderen Sachen einfach so zufällig.

**Comment by mee4895** [comment]
Can't reproduce and is possibly fixed in the nex version which is comming soon
