### ISSUE TITLE
Fehlermeldungen beim Zugriff auf Prüfungsitems bei Login als guest

### ISSUE THREAD

**Issue by colfes** [FIUS/Verleihsystem-TTF#71]
![grafik](https://user-images.githubusercontent.com/34137096/45370783-38d09000-b5e9-11e8-9050-797667109c7e.png)
Die Fehlermeldungen kommen alle, wenn man auf ein Prüfungsitem (welches für Guests eigentlich nicht sichtbar sein sollten, nur wenn sie falsch hochgeladen wurden) klickt während man als Guest eingeloggt ist.

**Comment by mee4895** [comment]
Works as intended the errors may be a little ambiguous but they essentially mean that the content can't be loaded because of access rights.
