### ISSUE TITLE
Warnmeldungen beim erstmaligen Bearbeiten eines Prüfungsitem

### ISSUE THREAD

**Issue by colfes** [FIUS/Verleihsystem-TTF#73]
Nachdem man nach Erstellen eines Prüfungsitems über die Itemseite des Prüfungsordners erstmalig das Prüfungsitem bearbeitet, erscheinen Warnmeldungen, dass Attribute (Prüfer, Semester etc.) fehlen, obwohl diese noch nicht existieren können.
(Stört den Workflow beim Hochladen, da man diese erst abwarten oder wegklicken muss)

**Comment by mee4895** [comment]
Fixed by #88
