### ISSUE TITLE
Errors beim Hinzufügen von Prüfungen

### ISSUE THREAD

**Issue by colfes** [FIUS/Verleihsystem-TTF#78]
Beim Hinzufügen von Prüfungen mit Firefox (Win10) erscheinen haufenweise Errors.
Workflow: Auswählen des Prüfungsordner, erstellen auf "NEW", dann Upload der Datei und Eintragen der Attribute. Dabei erscheinen Errors für jedes Attribut, dass man einfügt.
![grafik](https://user-images.githubusercontent.com/34137096/46412770-b2a6f580-c71f-11e8-852f-adb6cff2b458.png)

**Comment by mee4895** [comment]
Because the new version is on the horizon and we are unable to recreate the issue, it's probably and schema error. Please reopen the issue if the error persists after the update.
