### ISSUE TITLE
Sortierung der Prüfungen in der Suchfunktion

### ISSUE THREAD

**Issue by colfes** [FIUS/Verleihsystem-TTF#80]
Aktuell alphabetische Sortierung ist unpraktisch.
Vorschlag für Sortierung:
WS9900 < SS2000 < WS1516 < SS2018 etc.
plus Möglichkeit, von alt zu neu, bzw umgekehrt zu sortieren.

**Comment by mee4895** [comment]
Its not really sensible to do so, if you change the semester naming schema to sort lexicographically and ensure it is part of the name so everything sorts nicely. Since the system consists of mostly generic fields you would need specialized user settable sorting algorithms which is not practical.
