### ISSUE TITLE
500er HTTP Error beim Attribut ändern

### ISSUE THREAD

**Issue by TheMrPhantom** [FIUS/Verleihsystem-TTF#83]
Workflow:
1. In der Itemliste auf "+ New" drücken
2. Item erstellen
3. Attribut festlegen

Wenn ich versuche ein Attribut zu ändern kommt ein 500er Error vom Server
Error while retrieving resource "items/622/attributes/12".
500 Server error

**Comment by neumantm** [comment]
Mit welchem Account loggst du dich ein?

**Comment by TheMrPhantom** [comment]
Mit meinem ldap

**Comment by neumantm** [comment]
I've found out the problem was, that the item in question tried setting the name via the name schema, but had no parent, which was used in the schema.

I've created the following issues to help reduce the occurrences and improve the user information of this problem in the future: #86 and #87
